language: python
python:
  - "2.7"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
env:
  - DJANGO_VERSION=1.7.4
#  - DJANGO_VERSION=1.6
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install .
  - pip install django==$DJANGO_VERSION
  - pip install coveralls
before_script:
  - cd django-splitdate
# # command to run tests, e.g. python setup.py test
script:
  - python django-splitdate/tests/runtests.py

after_sucess:
  coveralls